services:
  vikpix-web:
    build:
      context: .
      args:
        VITE_AUTH_API_URL: ${VITE_AUTH_API_URL}
        VITE_APP_URL: ${VITE_APP_URL}
    expose:
      - "80"
    networks:
      - proxy